### ISSUE TITLE
NSInvalidArgumentException - unrecognized selector sent to instance

### ISSUE THREAD

**Issue by gaganspidey** [litt1e-p/UIScrollView-ScrollToTopBtn#1]
App crashes as soon as I begin scrolling the tableView. I am using Xcode 8.3. Here's the crash report:

`UIScrollView+ScrollToTopBtn[6040:151108] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSConcreteObservation floatValue]: unrecognized selector sent to instance 0x7c17ea70'`

The reason seems to be an invalid _offset_ value in the below method:
```
- (CGFloat)scrollToTopBtnShowOffset {
    id offset = objc_getAssociatedObject(self, @selector(scrollToTopBtnShowOffset));
    return offset > 0 ? [offset floatValue]: kScrollToTopBtnDefaultShowOffset;
}
```

How to resolve it?

**Comment by litt1e-p** [comment]
can you show how you assign the value of `scrollToTopBtnShowOffset `?

**Comment by gaganspidey** [comment]
Thanks for responding.

I haven't touched the code yet, I just cloned your project and executed it in Xcode. The default value is being used, ie., `self.tableView.scrollToTopBtnShowOffset = 700.f;`

Sometimes the crash is accompanied by a highlighted line:
https://imgur.com/a/IClmsbH

I've also noticed that the class name it points to in the exception varies:
`-[_NSConcreteObservation floatValue]`
`-[NSISRestrictedToZeroMarkerVariable floatValue]`

Here's a mini-recording for your needful:
https://www.dropbox.com/s/acfk2cct2rdekkr/UIScrollView-ScrollToTopBtn.mov?dl=0

**Comment by litt1e-p** [comment]
thanks. I will check it soon

**Comment by litt1e-p** [comment]
@gaganspidey there is no bug in my Xcode 9.3 & iOS 11 when I run the sample project, please give me more info about your environment

**Comment by gaganspidey** [comment]
On closer inspection it turned out that the crash happens only on iPhone 5 (removed in Xcode 9) and runs fine on all other devices.

A workaround that I've been able to figure out is not to assign any value to `scrollToTopBtnShowOffset ` and let it function on default terms.

**Comment by litt1e-p** [comment]
iPhone 5 is a 32bit device, maybe it is the reason, em..I will check it

**Comment by gaganspidey** [comment]
Nevermind I am closing this minor issue.
